WITH A AS (
    SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT E.ID, IFNULL(A.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA as E LEFT JOIN A
ON E.ID = A.PARENT_ID



