WITH MAX_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT m.YEAR, (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM ECOLI_DATA e LEFT JOIN MAX_ECOLI m ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY m.YEAR, YEAR_DEV