-- 코드를 작성해주세요
WITH INFO AS (
    SELECT n.FISH_TYPE, n.FISH_NAME, MAX(i.LENGTH) AS LENGTH
    FROM FISH_INFO i LEFT JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
    GROUP BY n.FISH_NAME, n.FISH_TYPE
)

SELECT f.ID, i.FISH_NAME, i.LENGTH
FROM FISH_INFO f INNER JOIN INFO i ON (f.LENGTH = i.LENGTH AND f.FISH_TYPE = i.FISH_TYPE)
ORDER BY f.ID