WITH w AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE desc
    LIMIT 1
)

SELECT w.SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES AS e INNER JOIN w ON e.EMP_NO = w.EMP_NO