WITH AVGSAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT d.DEPT_ID, d.DEPT_NAME_EN, s.AVG_SAL
FROM HR_DEPARTMENT d JOIN AVGSAL s ON d.DEPT_ID = s.DEPT_ID
ORDER BY AVG_SAL desc