WITH GRADES AS(
    SELECT CASE WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C' 
END AS GRADE, ID
    FROM DEVELOPERS
)

SELECT g.GRADE, d.ID, d.EMAIL
FROM DEVELOPERS d JOIN GRADES g ON d.ID = g.ID
WHERE g.GRADE IS NOT NULL
ORDER BY g.GRADE, d.ID